# Use the official Node.js image as the base image
FROM node:18 AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .
RUN chmod +x node_modules/.bin/vite

# Build the application
RUN npm run build

# Use a smaller image for the production environment
FROM nginx:alpine

# Copy the build output to the Nginx HTML directory
COPY --from=build /app/dist /usr/share/nginx/html
# Copy the custom Nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Expose port 8080
EXPOSE 8282

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]